const config = {
  // A secret value HTTP clients can use to authenticate with this script.
  // This value was generated by https://bitwarden.com/password-generator/
  SHARED_SECRET: "apple-banana-carrot-daikon-egg",

  // A string you want to precede the subject (subject line) of the emails
  // sent by this script.
  EMAIL_SUBJECT_PREFIX: "[curl-to-email]: ",
};